FROM chimbuko/mochi:latest

RUN git clone -b master https://github.com/celiafish/ChimbukoVisualizationII.git /ChimbukoVisualizationII && \
    cd /ChimbukoVisualizationII && \
    curl -O http://download.redis.io/redis-stable.tar.gz && \
    tar xvzf redis-stable.tar.gz &&  rm redis-stable.tar.gz && \
    cd redis-stable && make

WORKDIR /ChimbukoVisualizationII

RUN cd tests && \
    tar xvzf test.tar.gz

WORKDIR /ChimbukoVisualizationII
